In [2]:
import pandas as pd
import numpy as np
from numpy import nan
#import otter
#grader = otter.Notebook()

# <mark style="background: #843fa1; color: #ffffff;" >&nbsp;G </mark>&nbsp;Week 1: Working with Graphs 

------

### Instructions:

- Complete 50 points worth of questions to pass the assessment
- You can attempt any number of questions and in any order provided you pass at least 50 points.
- These questions should be attempted directly in this notebook.
- Be sure to check your work before submitting.
- Do not remove any provided markings from the answer spaces.
- Do not make any changes to this notebook outside of the answer spaces provided.
  
#### Submitting

- Reset your outputs before submitting by selecting the `Kernel` menu, then either `Restart & Run Clear Output` or `Restart & Run All`.
- Don't forget to save your notebook after this step.
- Submit your .ipynb file to Gradescope via upload.
- You can submit as many times as needed.
- When reviewing results, **ignore** any results listed under "Public Tests"  
  (There are no "Public Tests" in this assignment)

For more information, see the assessment page.

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Given the following undirected, unweighted graph:<br />
![unweighted undirected graph](https://zschub.github.io/img/unweighted-undirected.png)<br />
Write a function defined as:
```python
def edge_list():
```
that returns a list of edges where each edge is a set of two strings for the endpoint vertices of the edge. For example:
```python
def edge_list():
    return [{'0', '4'}, ...]
```
---
<details>
  <summary><span style="color:blue">What do I do?</span></summary>
   This is a manual task to record and return a set of edges from a graph image and serves as useful test data for following questions.
</details>

In [13]:
def edge_list():
    return [{'0','4'}, {'0','1'}, {'1', '2'}, {'3', '2'}, {'0', '3'}]
    # Write your solution here

[{'0', '4'}, {'0', '1'}, {'1', '2'}, {'2', '3'}, {'0', '3'}]

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def vertex_list(edge_list):
```
that examines a list of edges in the format used in Question 1 and extracts all of the vertices returning them in a set or `None` if the `edge_list` is empty. For example, the graph above (Qn 1) would return: 
```python
{'0', '1', '2', '3', '4'}
```

In [15]:
def vertex_list(edge_list):
    if edge_list == []:
        return None
    lst=[]
    # Write your solution here
    for i in edge_list:
        lst+=i
    return set(lst)
vertex_list([])

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def adjacency_list_as_dict (vertex_list, edge_list):
```
that accepts a list of vertices and list of edges in the format defined in Question 1 (list of sets of adjacent vertices) and returns an adjacency list in the form of a dictionary where the key defines the vertex and the values contain a list of adjacent vertices.

For example, given the graph shown in Question 1, the function would return a dict as follows:
```python
{'0': ['4', '1', '3'],
 '1': ['0', '2'],
 '2': ['1', '3'],
 '3': ['2', '0'],
 '4': ['0']}
```

In [20]:
def adjacency_list_as_dict (vertex_list, edge_list):
    dic = dict()
    vertex_list = sorted(list(vertex_list))
    for i in vertex_list:
        dic[i]=[]
    for i in edge_list:
        dic[list(i)[0]].append(list(i)[1])
        dic[list(i)[1]].append(list(i)[0])
    return dic
adjacency_list_as_dict(vertex_list(edge_list()),edge_list())

{'0': ['4', '1', '3'],
 '1': ['0', '2'],
 '2': ['1', '3'],
 '3': ['2', '0'],
 '4': ['0']}

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Given the following undirected, edge-weighted graph:<br />
![edge weighted undirected graph](https://zschub.github.io/img/undirected-edge-weighted.png)<br />
Write a function defined as:
```python
def edge_weighted_list():
```
that returns a list of edges where each edge is:
- a tuple containing two elements,
- firstly, a set of two strings for the endpoint vertices of the edge, and
- secondly, the weight of the edge.
For example:
```python
return [({'0', '4'}, 1), ...]
```
As for Question 1, this is a manual task of inspecting a graph and representing the edges and weights as a list and returning this from a function call.

In [23]:
def edge_weighted_list():

    # Write your solution here
    return [
        ({'4','0'},1),
        ({'0','1'},2),
        ({'1','2'},2),
        ({'2','3'},4),
        ({'3','0'},5)
    ]
edge_weighted_list()

[({'0', '4'}, 1),
 ({'0', '1'}, 2),
 ({'1', '2'}, 2),
 ({'2', '3'}, 4),
 ({'0', '3'}, 5)]

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```Python
def adjacency_list_with_weights (vertex_list, edge_list):
```
that returns an adjacency list where:
- keys represent vertices,
- values represent a list of adjacent vertices,
- for each adjacent vertex, a two value tuple is provided with `(adjacent vertex, weight of edge)`.

For example, given the graph above, the function would return:
```python
{'0': [('4', 1), ('1', 2), ('3', 5)],
 '1': [('0', 2), ('2', 2)],
 '2': [('1', 2), ('3', 4)],
 '3': [('0', 5), ('2', 4)],
 '4': [('0', 1)]}
```
although key and values ordering may be different.

In [30]:
def adjacency_list_with_weights (vertex_list, edge_list):

    # Write your solution here
    dic = dict()
    vertex_list = sorted(list(vertex_list))
    for i in vertex_list:
        dic[i]=[]
    for i in edge_list:
        dic[list(i[0])[0]].append((list(i[0])[1],list(i)[1]))
        dic[list(i[0])[1]].append((list(i[0])[0],list(i)[1]))
    return dic
adjacency_list_with_weights(vertex_list(edge_list()),edge_weighted_list())

{'0': [('4', 1), ('1', 2), ('3', 5)],
 '1': [('0', 2), ('2', 2)],
 '2': [('1', 2), ('3', 4)],
 '3': [('2', 4), ('0', 5)],
 '4': [('0', 1)]}

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def adjacency_list_directed (edge_list):
```
that returns an adjacency list of a graph defined as list of directed edges in the form of tuples:
```python
[(origin, destination), ...]
```
For example, in this graph, edges would be defined thus: 
```python
[(1, 2), (4, 0), ... ]
```<br />
![directed unweighted](https://zschub.github.io/img/directed-unweighted.jpg)<br />


In [36]:
e_list= [('0','1'),('1','2'),('2','3'),('3','4'),('4','0'),('3','0')]
def adjacency_list_directed (edge_list):
    # Write your solution here
    dic = dict()
    for i in edge_list:
        dic[i[0]]=[]
    for i in edge_list:
        dic[i[0]].append(i[1])
    return dic
adjacency_list_directed(e_list)


{'0': ['1'], '1': ['2'], '2': ['3'], '3': ['4', '0'], '4': ['0']}


#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def adjacency_matrix_weighted_directed (edge_list):
```    
that accepts a list of weighted, directed edges in the form of tuples:
```python
(origin, destination, weight)
```
for a graph of the form:<br />
![directed unweighted](https://zschub.github.io/img/directed-weighted.jpg)<br />
and returns an Adjacency Matrix as a pandas `DataFrame` with the following features:
- diagonal (identity) values are represented with the weight '0',
- non traversable edges are represented by `NumPy.nan`,
- column and index values match the vertex labels, and
- otherwise the matrix value represents the numeric weight of traversing the edge as a float value with index (row) as the origin and the column as the destination.

In [11]:
e_list= [('0','1',2),('1','2',2),('2','3',4),('3','4',3),('4','0',1),('3','0',5)]
def adjacency_matrix_weighted_directed (edge_list):
    # Write your solution here
    vertex_list = []
    for i in edge_list:
        vertex_list.extend([i[0],i[1]])
    vertex_list = sorted(set(vertex_list))
    ad_mat = np.empty((len(vertex_list),len(vertex_list)))
    ad_mat[:] = nan
    for i,val in enumerate(vertex_list):
        ad_mat[i][i]=0
    for i in edge_list:
        j,k = vertex_list.index(i[0]),vertex_list.index(i[1])
        ad_mat[j][k]=i[-1]
    return pd.DataFrame(ad_mat,index=vertex_list,columns=vertex_list)

adjacency_matrix_weighted_directed(e_list)

    

0    1    2    3    4
0  0.0  2.0  NaN  NaN  NaN
1  NaN  0.0  2.0  NaN  NaN
2  NaN  NaN  0.0  4.0  NaN
3  5.0  NaN  NaN  0.0  3.0
4  1.0  NaN  NaN  NaN  0.0

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def adjacency_matrix_unweighted_undirected (edge_list):
```
that returns a NumPy array with the adjacency matrix of a list of edges in the Question 1 format (a list of sets of adjacent vertices). 
- the axes of the array should reflect the sorted vertex values (so `'A', 'B', 'C'` rather than `'C', 'A', 'B'`.
- non adjacent vertices should be marked with 0,
- adjacent vertices should be marled with 1,
- looped vertices should be marked with 1, otherwise diagonal (identity) locations should be marked with 0.

Thus, a graph of the form:<br />
![directed unweighted](https://zschub.github.io/img/graph-basic.png)<br />should return:
```python
array([[0, 1, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 1, 0]])
```

In [31]:
edges = [{'A','B'}, {'B','C'}, {'B', 'D'}, {'C', 'D'}, {'D', 'D'}, {'A', 'E'}, {'E', 'D'}]
def adjacency_matrix_unweighted_undirected (edge_list):

    # Write your solution here
    vertex_list = []
    for i in edge_list:
        i = list(i)
        if len(i) == 1:
            vertex_list.extend([i[0],i[0]])
        else:
            vertex_list.extend([i[0],i[1]])
    vertex_list = sorted(set(vertex_list))
    ad_mat = np.zeros((len(vertex_list),len(vertex_list)))
    for i in edge_list:
        i = list(i)
        j,k = 0,0
        if len(i) == 1:
            j,k = vertex_list.index(i[0]),vertex_list.index(i[0])
        else:
            j,k = vertex_list.index(i[0]),vertex_list.index(i[1])
        ad_mat[j][k]=1
        ad_mat[k][j]=1
    return ad_mat.astype(int)
adjacency_matrix_unweighted_undirected(edges)

array([[0, 1, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 1, 0]])

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def degree_from_edges (edge_list, vertex):
```
that accepts a list of edges in the form of a list of sets (`[{'A', 'B'}, ...]`) and returns the degree of a vertex in the graph passed as a second parameter.

In [34]:
edges = [{'A','B'}, {'B','C'}, {'B', 'D'}, {'C', 'D'}, {'A', 'E'}, {'E', 'D'}]
def degree_from_edges (edge_list, vertex):
    count =0
    for i in edge_list:
        if vertex in list(i):
            count+=1
    return count
degree_from_edges(edges, 'B')

3

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def degrees_from_adjacency_matrix (adj_matrix):
```
that accepts a binary adjacency matrix formatted as per Question 8 (a NumPy array with adjacent vertices marked with 1 and otherwise 0) and returns a 1D `np.array` of integers being the degree of each vertex in the same sort order as the original indexing.

Thus, for the graph:<br /> ![unweighted undirected graph](https://zschub.github.io/img/unweighted-undirected.png)<br />
an input adjacency matrix:
```python
      [[0, 1, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0]]
```
would return:
```python
array([3, 2, 2, 2, 1])
```

In [37]:
def degrees_from_adjacency_matrix (adj_matrix): 
    lst =[]
    for i in adj_matrix:
        lst.append(sum(i))
    return np.array(lst)

array([3, 2, 2, 2, 1])

#### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def transform_list_to_matrix (adjacency_list):
```
that transforms an adjacency list for a directed graph (per Question 6 format: a dictionary where keys indicate vertex lables and values contain a list of adjacent (directed) vertices.

The function should construct a pandas `DataFrame` with the following features:
- diagonal (identity) values are represented with the value `0.0`,
- non traversable edges are represented by NumPy.nan,
- column and index values match the vertex labels, and
- traversable edges are indicated with the value `1.0` reading the directed adjacency matrix horizontally (the row shows the origin vertex and the column the destination).

Thus for the graph:<br />
![directed unweighted](https://zschub.github.io/img/directed-unweighted.jpg)<br />
represented by an adjacency list:
```python
{'0': ['1'], '1': ['2'], '2': ['3'], '3': ['4', '0'], '4': ['0']}
```
the `DataFrame` returned would have values:<br /><br />
![directed unweighted](https://zschub.github.io/img/adj-matrix.png)

In [54]:
def transform_list_to_matrix (adjacency_list):
    # Write your solution here
    indexs = sorted(list(adjacency_list.keys()))
    at_mat = np.empty((len(indexs),len(indexs)))
    at_mat[:] = nan
    for i,j in adjacency_list.items():
        at_mat[indexs.index(i)][indexs.index(i)]=0
        for k in j:
            at_mat[indexs.index(i)][indexs.index(k)]=1
    return pd.DataFrame(at_mat,index=indexs,columns=indexs)
alist = {'0': ['1'], '1': []}
amatrix = transform_list_to_matrix(alist)
amatrix.index

Index(['0', '1'], dtype='object')